### ISSUE TITLE
java.lang.NullPointerException at onPlaceholderRequest(CheckItemExpansion.java:583)

### ISSUE THREAD

**Issue by MarvinKlar** [PlaceholderAPI/CheckItem-Expansion#63]
I got the following error in my console: https://pastebin.com/eTCRYHcj

"java.lang.NullPointerException at com.extendedclip.papi.expansion.checkitem.CheckItemExpansion.onPlaceholderRequest(CheckItemExpansion.java:583)"

See https://github.com/PlaceholderAPI/PlaceholderAPI/issues/1027

**Comment by MarvinKlar** [comment]
@cj89898 Do you have any clue why I get this error?
