### ISSUE TITLE
GetInfo NBTInts and NBTStrings returning null value

### ISSUE THREAD

**Issue by TheCashFire** [PlaceholderAPI/CheckItem-Expansion#77]
After updating to PAPI 2.11.7-b200, CheckItem 2.7.8 post the most recent fixes, there appears to still be an issue with the nbtints and nbtstrings portions of getinfo. Trying to use a placeholder such as `%checkitem_getinfo:mainhand_nbtstrings:%` will return an empty string, whereas an actual check such as `%checkitem_getinfo:mainhand_nbtstrings:PublicBukkitValues..score:score-limit=1%`, which previously would return the value of score-limit, now throws an error akin to what you see below;

`java.lang.NullPointerException: Cannot invoke "de.shaded.checkitem.nbtapi.NBTCompound.getString(String)" because the return value of "de.shaded.checkitem.nbtapi.NBTItem.getCompound(String)" is null
        at com.extendedclip.papi.expansion.checkitem.CheckItemExpansion.onPlaceholderRequest(CheckItemExpansion.java:670) ~[?:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
        at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99) ~[PlaceholderAPI-2.11.6.jar:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.utils.StringUtils.replacePlaceholders(StringUtils.java:57) ~[DeluxeMenus-1.14.1.184.jar:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(MenuHolder.java:107) ~[DeluxeMenus-1.14.1.184.jar:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholdersAndArguments(MenuHolder.java:98) ~[DeluxeMenus-1.14.1.184.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.menu.MenuItem.getMenuItemLore(MenuItem.java:475) ~[DeluxeMenus-1.14.1.184.jar:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:250) ~[DeluxeMenus-1.14.1.184.jar:?]
        at DeluxeMenus-1.14.1.184.jar/com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$10(Menu.java:410) ~[DeluxeMenus-1.14.1.184.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-127-4e6a2a1]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

I can confirm that I an not the only one with this issue, I spent three days asking around HelpChat to see and others also have no solutions. Can someone take a look at this?

**Comment by TheCashFire** [comment]
Additional information, the expansion seems to work in these cases on spigot, but not on paper.
